---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job-st2-register-content
  labels:
    app: st2-register-content
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install, post-upgrade, post-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "7"
spec:
  template:
    metadata:
      name: job-st2-register-content
      labels:
        app: st2-register-content
        tier: backend
        vendor: stackstorm
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        # TODO: Investigate/propose running Helm hook only on condition when ConfigMap or Secret has changed
        checksum/config: {{ include (print $.Template.BasePath "/configmaps_st2-conf.yaml") . | sha256sum }}
        checksum/packs: {{ include (print $.Template.BasePath "/configmaps_packs.yaml") . | sha256sum }}
        {{- if .Values.jobs.annotations }}
          {{- toYaml .Values.jobs.annotations | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
      {{- if .Values.image.pullSecret }}
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if $.Values.st2.packs.images -}}
        {{- include "packs-pullSecrets" . | nindent 6 }}
      {{- end }}
      initContainers:
      {{- include "init-containers-wait-for-db" . | nindent 6 }}
      {{- if $.Values.st2.packs.images -}}
        {{- include "packs-initContainers" . | nindent 6 }}
      {{ end }}
      containers:
      - name: st2-register-content
        image: '{{ template "imageRepository" . }}/st2actionrunner:{{ tpl (.Values.jobs.image.tag | default (.Values.st2actionrunner.image.tag | default .Values.image.tag)) . }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - st2-register-content
          - --config-file=/etc/st2/st2.conf
          - --config-file=/etc/st2/st2.docker.conf
          - --config-file=/etc/st2/st2.user.conf
          - --register-all
          - --register-fail-on-failure
        volumeMounts:
        {{- include "st2-config-volume-mounts" . | nindent 8 }}
        - name: st2-pack-configs-vol
          mountPath: /opt/stackstorm/configs/
        {{- if .Values.st2.packs.images }}
        - name: st2-packs-vol
          mountPath: /opt/stackstorm/packs/
        - name: st2-virtualenvs-vol
          mountPath: /opt/stackstorm/virtualenvs/
        {{- end }}
        # TODO: Find out default resource limits for this specific service (#5)
        #resources:
      volumes:
        {{- include "st2-config-volume" . | nindent 8 }}
        - name: st2-pack-configs-vol
          configMap:
            name: {{ .Release.Name }}-st2-pack-configs
        {{- include "packs-volumes" $ | nindent 8 }}
      restartPolicy: OnFailure
    {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
    {{- end }}
    {{- with .Values.dnsConfig }}
      dnsConfig: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jobs.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jobs.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jobs.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}